import CoreModels
import Foundation

// Generated by Tools/developer-settings-ingest.mjs. Do not edit by hand.
public enum VisualDeveloperSettingsDefaults {
    public static let hologram = DeveloperSettingsSnapshot.Settings.Hologram(
        backdropBlurOpacity: 1.0,
        whiteFillOpacity: 0.56,
        lightenOpacity: 0.20,
        luminosityOpacity: 0.35,
        translationScaleX: 90,
        translationScaleY: 90,
        rotationDegrees: 30
    )

    public static let cardBackdrop = DeveloperSettingsSnapshot.Settings.CardBackdrop(
        depthScale: 5.0,
        hideBackdrop: false,
        reverseDepthOrder: false,
        reverseMotionDirection: true,
        rotationGuillocheMovesInsteadOfRotates: false,
        guillocheMovementScaleX: 0.8,
        guillocheMovementScaleY: 0.8
    )

    public static let diagnostics = DeveloperSettingsSnapshot.Settings.Diagnostics(
        showsCardAnimationOverlay: false
    )

    public static let gradientAndFiligree = DeveloperSettingsSnapshot.Settings.GradientAndFiligree(
        emptyStateEdgeReach: 1.0,
        emptyStateRotationDegrees: 90,
        cardRotationDegrees: 45,
        emptyStateOpacity: 0.3,
        cardOpacity: 0.2,
        cardPhotoOpacity: 0.23
    )

    public static let elementDepth = DeveloperSettingsSnapshot.Settings.ElementDepth(
        perspectiveAmount: 1.0,
        isSkewEnabled: false,
        skewAmount: 0.08,
        moonPhaseLayer: 12,
        zodiacGlyphLayer: 4,
        zodiacConstellationLayer: 12
    )

    public static let zodiacAndPhoto = DeveloperSettingsSnapshot.Settings.ZodiacAndPhoto(
        zodiacRotationDegrees: 300,
        photoFaceZoom: 0.0,
        photoOpacity: 0.35
    )

    public static let mediumCard = DeveloperSettingsSnapshot.Settings.MediumCard(
        aspectRatio: 1.0
    )
}
