import Foundation

// Usage: svg-to-swift <input-dir> <output-dir> <namespace>
// Scans <input-dir> for *.svg, parses each <path d="..."> element, and emits
// one Swift file per SVG into <output-dir>, with all paths under <namespace>.

let arguments = CommandLine.arguments
guard arguments.count == 4 else {
    FileHandle.standardError.write(Data("Usage: svg-to-swift <input-dir> <output-dir> <namespace>\n".utf8))
    exit(2)
}

let inputDir = URL(fileURLWithPath: arguments[1])
let outputDir = URL(fileURLWithPath: arguments[2])
let namespace = arguments[3]

try FileManager.default.createDirectory(at: outputDir, withIntermediateDirectories: true)

// Optional sidecar JSON next to the SVGs, keyed by SVG basename (without
// extension), value = human-readable reason for reversal. Any basename listed
// has its `[Path]` order flipped in the emitted `all` array — used to correct
// designer SVGs whose layer order paints/animates the wrong direction.
//
// Example `path-order-overrides.json`:
// {
//     "A_Circle": "Source SVG layered outside-in; reverse so animation winds inward"
// }
let overridesURL = inputDir.appendingPathComponent("path-order-overrides.json")
let reverseOrder: Set<String> = {
    guard let data = try? Data(contentsOf: overridesURL),
          let json = try? JSONSerialization.jsonObject(with: data) as? [String: String]
    else { return [] }
    return Set(json.keys)
}()
if !reverseOrder.isEmpty {
    print("Reversing path order for: \(reverseOrder.sorted().joined(separator: ", "))")
}

let svgFiles = (try? FileManager.default.contentsOfDirectory(at: inputDir, includingPropertiesForKeys: nil))
    .map { $0.filter { $0.pathExtension.lowercased() == "svg" } } ?? []

for svgFile in svgFiles {
    let name = svgFile.deletingPathExtension().lastPathComponent
    let contents = try String(contentsOf: svgFile, encoding: .utf8)

    // Extract every d="..." attribute. Quick regex — the designer's SVGs use
    // straightforward attribute syntax; if they ever get nested CDATA we'd
    // need a real XML parser.
    // Match only d= attributes on <path> elements. A simple word boundary before `d`
    // avoids false positives on e.g. `id="..."` where `d="..."` appears as a suffix.
    let pattern = #"(?:^|\s)d\s*=\s*"([^"]*)""#
    let regex = try NSRegularExpression(pattern: pattern)
    let matches = regex.matches(in: contents, range: NSRange(contents.startIndex..., in: contents))

    var paths: [(name: String, commands: [PathCommand])] = []
    for (index, match) in matches.enumerated() {
        guard let range = Range(match.range(at: 1), in: contents) else { continue }
        let dString = String(contents[range])
        let commands = try SVGParser.parse(d: dString)
        paths.append((name: "path\(index)", commands: commands))
    }

    // Reverse path order for any basename listed in path-order-overrides.json
    // — flipping the array also flips the per-index stagger animations and
    // the paint order in `[Path].all`, which is how the user reverses the
    // animation direction for SVGs whose source layers are wound the wrong
    // way. The path constants themselves still have stable `path0…pathN`
    // names; only the order in `all` changes. Renaming so `path0` is the
    // first painted path keeps callers that rely on `.first` consistent
    // with the visible ordering.
    let pathsWithContainer: [(name: String, commands: [PathCommand])] = {
        guard reverseOrder.contains(name) else { return paths }
        return paths.reversed().enumerated().map { offset, element in
            (name: "path\(offset)", commands: element.commands)
        }
    }()

    // Declare the per-file nested enum as an extension on the parent namespace,
    // then fill that nested enum with path constants via a second extension.
    // This keeps the namespace scope (e.g. `CCVisuals.Guilloche.Rotation.A_Rotation`)
    // reachable without polluting the global namespace.
    let fileURL = outputDir.appendingPathComponent("\(name).swift")
    let preamble = "// Auto-generated by SVGToSwift. Do not edit.\nimport SwiftUI\n\npublic extension \(namespace) {\n    enum \(name) {}\n}\n\n"
    let body = SwiftEmitter.emitFile(namespace: "\(namespace).\(name)", paths: pathsWithContainer, moduleImports: [])
    try (preamble + body).write(to: fileURL, atomically: true, encoding: .utf8)

    print("Generated \(fileURL.path) — \(paths.count) paths")
}

print("Done. Processed \(svgFiles.count) SVG files.")
