import Foundation

// Usage: svg-to-swift <input-dir> <output-dir> <namespace>
// Scans <input-dir> for *.svg, parses each <path d="..."> element, and emits
// one Swift file per SVG into <output-dir>, with all paths under <namespace>.

let arguments = CommandLine.arguments
guard arguments.count == 4 else {
    FileHandle.standardError.write(Data("Usage: svg-to-swift <input-dir> <output-dir> <namespace>\n".utf8))
    exit(2)
}

let inputDir = URL(fileURLWithPath: arguments[1])
let outputDir = URL(fileURLWithPath: arguments[2])
let namespace = arguments[3]

try FileManager.default.createDirectory(at: outputDir, withIntermediateDirectories: true)

let svgFiles = (try? FileManager.default.contentsOfDirectory(at: inputDir, includingPropertiesForKeys: nil))
    .map { $0.filter { $0.pathExtension.lowercased() == "svg" } } ?? []

for svgFile in svgFiles {
    let name = svgFile.deletingPathExtension().lastPathComponent
    let contents = try String(contentsOf: svgFile, encoding: .utf8)

    // Extract every d="..." attribute. Quick regex — the designer's SVGs use
    // straightforward attribute syntax; if they ever get nested CDATA we'd
    // need a real XML parser.
    // Match only d= attributes on <path> elements. A simple word boundary before `d`
    // avoids false positives on e.g. `id="..."` where `d="..."` appears as a suffix.
    let pattern = #"(?:^|\s)d\s*=\s*"([^"]*)""#
    let regex = try NSRegularExpression(pattern: pattern)
    let matches = regex.matches(in: contents, range: NSRange(contents.startIndex..., in: contents))

    var paths: [(name: String, commands: [PathCommand])] = []
    for (index, match) in matches.enumerated() {
        guard let range = Range(match.range(at: 1), in: contents) else { continue }
        let dString = String(contents[range])
        let commands = try SVGParser.parse(d: dString)
        paths.append((name: "path\(index)", commands: commands))
    }

    let pathsWithContainer: [(name: String, commands: [PathCommand])] = paths

    // Declare the per-file nested enum as an extension on the parent namespace,
    // then fill that nested enum with path constants via a second extension.
    // This keeps the namespace scope (e.g. `CCVisuals.Guilloche.Rotation.A_Rotation`)
    // reachable without polluting the global namespace.
    let fileURL = outputDir.appendingPathComponent("\(name).swift")
    let preamble = "// Auto-generated by SVGToSwift. Do not edit.\nimport SwiftUI\n\npublic extension \(namespace) {\n    enum \(name) {}\n}\n\n"
    let body = SwiftEmitter.emitFile(namespace: "\(namespace).\(name)", paths: pathsWithContainer, moduleImports: [])
    try (preamble + body).write(to: fileURL, atomically: true, encoding: .utf8)

    print("Generated \(fileURL.path) — \(paths.count) paths")
}

print("Done. Processed \(svgFiles.count) SVG files.")
