import Foundation

public enum SwiftEmitter {

    /// Emit Swift source that declares a `Path` constant built from the command list.
    /// Caller is responsible for wrapping the output in the right scope (extension, struct, etc.).
    public static func emit(pathCommands: [PathCommand], constantName: String) -> String {
        var body = "    static let \(constantName) = Path { path in\n"
        for command in pathCommands {
            switch command {
            case .moveTo(let x, let y):
                body += "        path.move(to: CGPoint(x: \(x), y: \(y)))\n"
            case .lineTo(let x, let y):
                body += "        path.addLine(to: CGPoint(x: \(x), y: \(y)))\n"
            case .cubicBezier(let c1x, let c1y, let c2x, let c2y, let x, let y):
                body += "        path.addCurve(to: CGPoint(x: \(x), y: \(y)), control1: CGPoint(x: \(c1x), y: \(c1y)), control2: CGPoint(x: \(c2x), y: \(c2y)))\n"
            case .quadraticBezier(let cx, let cy, let x, let y):
                body += "        path.addQuadCurve(to: CGPoint(x: \(x), y: \(y)), control: CGPoint(x: \(cx), y: \(cy)))\n"
            case .closePath:
                body += "        path.closeSubpath()\n"
            }
        }
        body += "    }"
        return body
    }

    /// Emit a full Swift file for multiple named paths inside a namespace.
    /// Appends a `static let all: [Path]` convenience array listing every emitted
    /// path in declaration order, so callers can iterate without reflection.
    public static func emitFile(
        namespace: String,
        paths: [(name: String, commands: [PathCommand])],
        moduleImports: [String] = ["SwiftUI"]
    ) -> String {
        var output = "// Auto-generated by SVGToSwift. Do not edit.\n"
        for module in moduleImports {
            output += "import \(module)\n"
        }
        output += "\npublic extension \(namespace) {\n"
        for (name, commands) in paths {
            output += emit(pathCommands: commands, constantName: name) + "\n\n"
        }
        // Append convenience `all` array so callers can enumerate without reflection.
        let allEntries = paths.map { "        \($0.name)" }.joined(separator: ",\n")
        if paths.isEmpty {
            output += "    static let all: [Path] = []\n"
        } else {
            output += "    static let all: [Path] = [\n\(allEntries)\n    ]\n"
        }
        output += "}\n"
        return output
    }
}
