import Foundation

// Generated by Tools/developer-settings-ingest.mjs. Do not edit by hand.
public enum CoreDeveloperSettingsDefaults {
    public static let motion = DeveloperSettingsSnapshot.Settings.Motion(
        relativeFullScaleDegrees: 45,
        saveButtonGradientGain: 2.5,
        zeroPointSettleDuration: 2.0
    )
}
